
[platformio]
workspace_dir = .pio.nosync
default_envs = mqttAerosolSensor

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_ldf_mode = deep
lib_archive = false
lib_deps = 
    tzapu/WiFiManager @ ^2.0.17
    knolleary/PubSubClient
    FS
    LittleFS
    bblanchon/ArduinoJson @ ^7.0.4
    https://github.com/fu-hsi/PMS.git

[env:mqttAerosolSensor]
upload_speed = 460800   ;230400
build_flags =
    -DPIN_PM_RX=16
    -DPIN_PM_TX=17
    -DPIN_PM_ENABLE=4
    -DPIN_PM_RESET=15
    -DPIN_ERASE_WIFI=0
    -DPM_NEVER_SLEEPS
;    -DTOPIC_DATA="\"luchtsensor/data\""
    -DLOG_LEVEL=LOG_LEVEL_DEBUG
